/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author Mamore e Ika
 */
public class AcercaDe extends javax.swing.JFrame {
    
    /**
     * Creates new form AcercaDe
     * @param parent
     */
    public AcercaDe(JFrame parent) {
        initComponents();
        customizeComponents();
        setupBehavior(parent);
    }
    private void customizeComponents() {
        setTitle("Acerca de TheBarberShop");
        setSize(422, 330);
        setResizable(false);
        
        // Configurar contenido (usando tus componentes jPlAcercaDe, jScrollPane1, etc.)
        jTPacercaDe.setContentType("text/html");
        jTPacercaDe.setText("<html><center><h2>TheBarberShop</h2>"
                + "<p>Versión 1.0</p>"
                + "<p>© 2025 Propiedad de Ancharja Studios </p>"
                + "<p>Sistema de gestión para barberías</p></center></html>");
    }

    private void setupBehavior(JFrame parent) {
        // 1. Deshabilitar operación de cierre por defecto
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        // 2. Cerrar solo al perder foco
        setLocationRelativeTo(parent);
        addWindowFocusListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                dispose();
            }
        });
        
        
        // 3. Opcional: Permitir cerrar con ESC
        JRootPane rootPane = SwingUtilities.getRootPane(jPlAcercaDe);
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke("ESCAPE"), "close");
        rootPane.getActionMap().put("close", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlAcercaDe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPacercaDe = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlAcercaDe.setBackground(new java.awt.Color(51, 51, 51));
        jPlAcercaDe.setName(""); // NOI18N
        jPlAcercaDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPacercaDe.setBackground(new java.awt.Color(102, 102, 102));
        jTPacercaDe.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jTPacercaDe.setEnabled(false);
        jScrollPane1.setViewportView(jTPacercaDe);

        jPlAcercaDe.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 260));

        getContentPane().add(jPlAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form
        java.awt.EventQueue.invokeLater(() -> new AcercaDe().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPlAcercaDe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTPacercaDe;
    // End of variables declaration//GEN-END:variables

    private void setModalityType(Dialog.ModalityType modalityType) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
