/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import java.util.Date; // Para el JCalendar
import java.text.SimpleDateFormat; // Para formatear la fecha a String
import javax.swing.JOptionPane; // Para los mensajes emergentes
/**
 *
 * @author jaelj
 */
public class AgendarCita extends javax.swing.JFrame {

    public AgendarCita() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLTituloAgendarcita = new javax.swing.JLabel();
        JcomboTipodeservicio = new javax.swing.JComboBox<>();
        JLtipodeservicio = new javax.swing.JLabel();
        JSPnotasadicionales = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JLnotasadicionales = new javax.swing.JLabel();
        JBcancelar = new javax.swing.JButton();
        JBagendarcita = new javax.swing.JButton();
        JComboElegirbarbero = new javax.swing.JComboBox<>();
        JLElegirbarbero = new javax.swing.JLabel();
        JLfechadelacita = new javax.swing.JLabel();
        JComboHORA = new javax.swing.JComboBox<>();
        JLhora = new javax.swing.JLabel();
        JComboLugarcita = new javax.swing.JComboBox<>();
        JLlugarcita = new javax.swing.JLabel();
        Jcalendario = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png")));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagenn(1).jpg")));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Agendar Cita");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLTituloAgendarcita.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        JLTituloAgendarcita.setForeground(new java.awt.Color(255, 255, 255));
        JLTituloAgendarcita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTituloAgendarcita.setText("Agenda tu cita");
        JLTituloAgendarcita.setToolTipText("");
        jPanel1.add(JLTituloAgendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 230, -1));

        JcomboTipodeservicio.setBackground(new java.awt.Color(153, 153, 153));
        JcomboTipodeservicio.setForeground(new java.awt.Color(0, 0, 0));
        JcomboTipodeservicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Servicio...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        JcomboTipodeservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboTipodeservicioActionPerformed(evt);
            }
        });
        jPanel1.add(JcomboTipodeservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 140, 30));

        JLtipodeservicio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLtipodeservicio.setForeground(new java.awt.Color(255, 255, 255));
        JLtipodeservicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtipodeservicio.setText("Tipo de servicio:");
        jPanel1.add(JLtipodeservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 140, 20));

        JSPnotasadicionales.setToolTipText("");
        JSPnotasadicionales.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        JSPnotasadicionales.setViewportView(jScrollPane1);

        jPanel1.add(JSPnotasadicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 220, 90));

        JLnotasadicionales.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLnotasadicionales.setForeground(new java.awt.Color(255, 255, 255));
        JLnotasadicionales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnotasadicionales.setText("Notas adicionales (opcional)");
        jPanel1.add(JLnotasadicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 220, 20));

        JBcancelar.setBackground(new java.awt.Color(102, 0, 0));
        JBcancelar.setText("Cancelar");
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(JBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, 30));

        JBagendarcita.setBackground(new java.awt.Color(51, 102, 0));
        JBagendarcita.setForeground(new java.awt.Color(255, 255, 255));
        JBagendarcita.setText("Agendar");
        JBagendarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagendarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(JBagendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 30));

        JComboElegirbarbero.setBackground(new java.awt.Color(153, 153, 153));
        JComboElegirbarbero.setForeground(new java.awt.Color(0, 0, 0));
        JComboElegirbarbero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Barbero...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        JComboElegirbarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboElegirbarberoActionPerformed(evt);
            }
        });
        jPanel1.add(JComboElegirbarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 30));

        JLElegirbarbero.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLElegirbarbero.setForeground(new java.awt.Color(255, 255, 255));
        JLElegirbarbero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLElegirbarbero.setText("Seleccione Barbero:");
        jPanel1.add(JLElegirbarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        JLfechadelacita.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLfechadelacita.setForeground(new java.awt.Color(255, 255, 255));
        JLfechadelacita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfechadelacita.setText("Fecha de la Cita:");
        jPanel1.add(JLfechadelacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 140, 30));

        JComboHORA.setBackground(new java.awt.Color(153, 153, 153));
        JComboHORA.setForeground(new java.awt.Color(0, 0, 0));
        JComboHORA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione hora...", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "08:00 PM", "09:00 PM", "10:00 PM" }));
        JComboHORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboHORAActionPerformed(evt);
            }
        });
        jPanel1.add(JComboHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 30));

        JLhora.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLhora.setForeground(new java.awt.Color(255, 255, 255));
        JLhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLhora.setText("Hora:");
        jPanel1.add(JLhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 20));

        JComboLugarcita.setBackground(new java.awt.Color(153, 153, 153));
        JComboLugarcita.setForeground(new java.awt.Color(0, 0, 0));
        JComboLugarcita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion lugar...", "1", "2", "3", "4", "5", " " }));
        jPanel1.add(JComboLugarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 140, 30));

        JLlugarcita.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JLlugarcita.setForeground(new java.awt.Color(255, 255, 255));
        JLlugarcita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLlugarcita.setText("Lugar de Cita:");
        jPanel1.add(JLlugarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 140, 20));
        jPanel1.add(Jcalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 330, 210));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        jPanel1.add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuCliente().setVisible(true);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void JBagendarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagendarcitaActionPerformed
        // Obtener la fecha seleccionada del calendario
    Date fechaSeleccionada = Jcalendario.getDate();
    if (fechaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha en el calendario.");
        return;
    }

    // Validar que la fecha seleccionada no sea anterior a hoy (solo comparar días)
    java.util.Calendar calFecha = java.util.Calendar.getInstance();
    calFecha.setTime(fechaSeleccionada);
    calFecha.set(java.util.Calendar.HOUR_OF_DAY, 0);
    calFecha.set(java.util.Calendar.MINUTE, 0);
    calFecha.set(java.util.Calendar.SECOND, 0);
    calFecha.set(java.util.Calendar.MILLISECOND, 0);

    java.util.Calendar calHoy = java.util.Calendar.getInstance();
    calHoy.set(java.util.Calendar.HOUR_OF_DAY, 0);
    calHoy.set(java.util.Calendar.MINUTE, 0);
    calHoy.set(java.util.Calendar.SECOND, 0);
    calHoy.set(java.util.Calendar.MILLISECOND, 0);

    if (calFecha.before(calHoy)) {
        JOptionPane.showMessageDialog(this, "¡No puedes agendar citas en fechas pasadas!");
        return;
    }

    // Formatear la fecha como String para mostrarla
    String fechaStr = new SimpleDateFormat("yyyy-MM-dd").format(fechaSeleccionada);

    // Obtener la hora seleccionada
    String horaSeleccionada = (String) JComboHORA.getSelectedItem();
    if (horaSeleccionada == null || horaSeleccionada.equals("Seleccione hora...")) {
        JOptionPane.showMessageDialog(this, "Seleccione una hora.");
        return;
    }

    // Obtener el barbero seleccionado
    String barbero = (String) JComboElegirbarbero.getSelectedItem();
    if (barbero == null || barbero.equals("Seleccione Barbero...")) {
        JOptionPane.showMessageDialog(this, "Seleccione un barbero.");
        return;
    }

    // Obtener el tipo de servicio seleccionado
    String servicio = (String) JcomboTipodeservicio.getSelectedItem();
    if (servicio == null || servicio.equals("Seleccione Servicio...")) {
        JOptionPane.showMessageDialog(this, "Seleccione un tipo de servicio.");
        return;
    }

    // Obtener el lugar de la cita seleccionado
    String lugar = (String) JComboLugarcita.getSelectedItem();
    if (lugar == null || lugar.equals("Seleccion lugar...")) {
        JOptionPane.showMessageDialog(this, "Seleccione un lugar para la cita.");
        return;
    }

    // Obtener notas adicionales (opcional)
    String notas = jTextArea1.getText();

    // --- Aquí iría la lógica para guardar en la base de datos ---
    // TODO: agregar código para guardar la cita en la base de datos

    // Mensaje de confirmación
    JOptionPane.showMessageDialog(this, "¡Cita agendada para el " + fechaStr + " a las " + horaSeleccionada + "!\nBarbero: " + barbero + "\nServicio: " + servicio + "\nLugar: " + lugar + "\nNotas: " + notas);
    }//GEN-LAST:event_JBagendarcitaActionPerformed

    private void JComboHORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboHORAActionPerformed
        
    }//GEN-LAST:event_JComboHORAActionPerformed

    private void JcomboTipodeservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboTipodeservicioActionPerformed
        
    }//GEN-LAST:event_JcomboTipodeservicioActionPerformed

    private void JComboElegirbarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboElegirbarberoActionPerformed
        
    }//GEN-LAST:event_JComboElegirbarberoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new MenuCliente().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarCita().setVisible(true);
            }
        });
    }   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagendarcita;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JComboBox<String> JComboElegirbarbero;
    private javax.swing.JComboBox<String> JComboHORA;
    private javax.swing.JComboBox<String> JComboLugarcita;
    private javax.swing.JLabel JLElegirbarbero;
    private javax.swing.JLabel JLTituloAgendarcita;
    private javax.swing.JLabel JLfechadelacita;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLhora;
    private javax.swing.JLabel JLlugarcita;
    private javax.swing.JLabel JLnotasadicionales;
    private javax.swing.JLabel JLtipodeservicio;
    private javax.swing.JScrollPane JSPnotasadicionales;
    private com.toedter.calendar.JCalendar Jcalendario;
    private javax.swing.JComboBox<String> JcomboTipodeservicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
