/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import java.util.Date; // Para el JCalendar
import java.text.SimpleDateFormat; // Para formatear la fecha a String
import javax.swing.JOptionPane; // Para los mensajes emergentes
import thebarbershop.utilidades.CitaDAO;
import java.util.Calendar;
import java.util.List;
/**
 *
 * @author jaelj
 */
public class AgendarCita extends javax.swing.JFrame {
    private final String emailUsuario;
    public AgendarCita(String email) {
        this.emailUsuario = email;
        initComponents();
        Jcalendario.addPropertyChangeListener(this::JcalendarioPropertyChange);
        setLocationRelativeTo(null);
        // Cargar datos desde la BD
        CitaDAO.cargarBarberos(JComboElegirbarbero);
        CitaDAO.cargarServicios(JcomboTipodeservicio);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLTituloAgendarcita = new javax.swing.JLabel();
        JcomboTipodeservicio = new javax.swing.JComboBox<>();
        JLtipodeservicio = new javax.swing.JLabel();
        JSPnotasadicionales = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCerrarApp2 = new javax.swing.JButton();
        JLnotasadicionales = new javax.swing.JLabel();
        JBcancelar = new javax.swing.JButton();
        JBagendarcita = new javax.swing.JButton();
        JComboElegirbarbero = new javax.swing.JComboBox<>();
        JLElegirbarbero = new javax.swing.JLabel();
        JLfechadelacita = new javax.swing.JLabel();
        JComboHORA = new javax.swing.JComboBox<>();
        JLhora = new javax.swing.JLabel();
        JComboLugarcita = new javax.swing.JComboBox<>();
        JLlugarcita = new javax.swing.JLabel();
        Jcalendario = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png")));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagenn(1).jpg")));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Agendar Cita");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLTituloAgendarcita.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        JLTituloAgendarcita.setForeground(new java.awt.Color(255, 255, 255));
        JLTituloAgendarcita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTituloAgendarcita.setText("Agenda tu cita");
        JLTituloAgendarcita.setToolTipText("");
        jPanel1.add(JLTituloAgendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 530, -1));

        JcomboTipodeservicio.setBackground(new java.awt.Color(153, 153, 153));
        JcomboTipodeservicio.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JcomboTipodeservicio.setForeground(new java.awt.Color(0, 0, 0));
        JcomboTipodeservicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Servicio...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        JcomboTipodeservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboTipodeservicioActionPerformed(evt);
            }
        });
        jPanel1.add(JcomboTipodeservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 50));

        JLtipodeservicio.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLtipodeservicio.setForeground(new java.awt.Color(255, 255, 255));
        JLtipodeservicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtipodeservicio.setText("Tipo de servicio:");
        jPanel1.add(JLtipodeservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 230, 30));

        JSPnotasadicionales.setToolTipText("");
        JSPnotasadicionales.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        JSPnotasadicionales.setViewportView(jScrollPane1);

        jPanel1.add(JSPnotasadicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 190, 120));

        btnCerrarApp2.setBackground(new java.awt.Color(153, 0, 51));
        btnCerrarApp2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnCerrarApp2.setText("Salir");
        btnCerrarApp2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarApp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarApp2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarApp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 190, 50));

        JLnotasadicionales.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLnotasadicionales.setForeground(new java.awt.Color(255, 255, 255));
        JLnotasadicionales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnotasadicionales.setText("Notas adicionales");
        jPanel1.add(JLnotasadicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 190, 30));

        JBcancelar.setBackground(new java.awt.Color(153, 0, 51));
        JBcancelar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        JBcancelar.setForeground(new java.awt.Color(255, 255, 255));
        JBcancelar.setText("Cancelar");
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(JBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 190, 50));

        JBagendarcita.setBackground(new java.awt.Color(51, 102, 0));
        JBagendarcita.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        JBagendarcita.setForeground(new java.awt.Color(255, 255, 255));
        JBagendarcita.setText("Agendar");
        JBagendarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagendarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(JBagendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 190, 50));

        JComboElegirbarbero.setBackground(new java.awt.Color(153, 153, 153));
        JComboElegirbarbero.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JComboElegirbarbero.setForeground(new java.awt.Color(0, 0, 0));
        JComboElegirbarbero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Barbero...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        JComboElegirbarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboElegirbarberoActionPerformed(evt);
            }
        });
        jPanel1.add(JComboElegirbarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 230, 50));

        JLElegirbarbero.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLElegirbarbero.setForeground(new java.awt.Color(255, 255, 255));
        JLElegirbarbero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLElegirbarbero.setText("Seleccione Barbero:");
        jPanel1.add(JLElegirbarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 30));

        JLfechadelacita.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLfechadelacita.setForeground(new java.awt.Color(255, 255, 255));
        JLfechadelacita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfechadelacita.setText("Fecha de la Cita:");
        jPanel1.add(JLfechadelacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 330, 30));

        JComboHORA.setBackground(new java.awt.Color(153, 153, 153));
        JComboHORA.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JComboHORA.setForeground(new java.awt.Color(0, 0, 0));
        JComboHORA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione hora...", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "08:00 PM", "09:00 PM", "10:00 PM" }));
        JComboHORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboHORAActionPerformed(evt);
            }
        });
        jPanel1.add(JComboHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, 50));

        JLhora.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLhora.setForeground(new java.awt.Color(255, 255, 255));
        JLhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLhora.setText("Hora:");
        jPanel1.add(JLhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 230, 30));

        JComboLugarcita.setBackground(new java.awt.Color(153, 153, 153));
        JComboLugarcita.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JComboLugarcita.setForeground(new java.awt.Color(0, 0, 0));
        JComboLugarcita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion lugar...", "1", "2", "3", "4", "5", " " }));
        jPanel1.add(JComboLugarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 230, 50));

        JLlugarcita.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLlugarcita.setForeground(new java.awt.Color(255, 255, 255));
        JLlugarcita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLlugarcita.setText("Lugar de Cita:");
        jPanel1.add(JLlugarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 30));

        Jcalendario.setBackground(new java.awt.Color(51, 51, 51));
        Jcalendario.setForeground(new java.awt.Color(51, 51, 51));
        Jcalendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JcalendarioPropertyChange(evt);
            }
        });
        jPanel1.add(Jcalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 330, 230));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Volver al menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 190, 50));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        jPanel1.add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuCliente(emailUsuario).setVisible(true);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void JBagendarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagendarcitaActionPerformed
        Date fechaSeleccionada = Jcalendario.getDate();
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha.");
            return;
        }

        // Validar fecha no pasada
        Calendar calFecha = Calendar.getInstance();
        calFecha.setTime(fechaSeleccionada);
        calFecha.set(Calendar.HOUR_OF_DAY, 0);
        calFecha.set(Calendar.MINUTE, 0);

        Calendar calHoy = Calendar.getInstance();
        calHoy.set(Calendar.HOUR_OF_DAY, 0);
        calHoy.set(Calendar.MINUTE, 0);

        if (calFecha.before(calHoy)) {
            JOptionPane.showMessageDialog(this, "No puedes agendar citas en fechas pasadas.");
            return;
        }

        // Obtener día de la semana
        String[] dias = {"", "DOMINGO", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADOS"};
        String diaSemana = dias[calFecha.get(Calendar.DAY_OF_WEEK)];

        String hora = (String) JComboHORA.getSelectedItem();
        String barbero = (String) JComboElegirbarbero.getSelectedItem();
        String servicio = (String) JcomboTipodeservicio.getSelectedItem();
        String lugar = (String) JComboLugarcita.getSelectedItem();
        String notas = jTextArea1.getText();

        // Validaciones
        if (hora == null || hora.equals("Seleccione hora...") || hora.equals("No trabaja este día")) {
            JOptionPane.showMessageDialog(this, "Seleccione una hora válida.");
            return;
        }
        if (barbero == null || barbero.equals("Seleccione Barbero...")) {
            JOptionPane.showMessageDialog(this, "Seleccione un barbero.");
            return;
        }
        if (servicio == null || servicio.equals("Seleccione Servicio...")) {
            JOptionPane.showMessageDialog(this, "Seleccione un servicio.");
            return;
        }
        if (lugar == null || lugar.equals("Seleccion lugar...")) {
            JOptionPane.showMessageDialog(this, "Seleccione un lugar.");
            return;
        }

        // Formato fecha: yyyy-MM-dd HH:mm:ss
        String fechaStr = new SimpleDateFormat("yyyy-MM-dd").format(fechaSeleccionada) + " " + hora + ":00";

        // Verificar disponibilidad (doble verificación)
        if (!CitaDAO.esDisponible(barbero, fechaStr.split(" ")[0], hora)) {
            JOptionPane.showMessageDialog(this, "El barbero ya tiene una cita en ese horario.");
            return;
        }

        // Agendar cita
        if (CitaDAO.agendarCita(emailUsuario, barbero, servicio, fechaStr.split(" ")[0], hora, notas)) {
            JOptionPane.showMessageDialog(this, "Cita agendada con éxito.");
            this.dispose();
            new MenuCliente(emailUsuario).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error al agendar la cita.");
        }
    }//GEN-LAST:event_JBagendarcitaActionPerformed

    private void JComboHORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboHORAActionPerformed
        
    }//GEN-LAST:event_JComboHORAActionPerformed

    private void JcomboTipodeservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboTipodeservicioActionPerformed
        
    }//GEN-LAST:event_JcomboTipodeservicioActionPerformed

    private void JComboElegirbarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboElegirbarberoActionPerformed
        // Limpiar combo de horas
        JComboHORA.removeAllItems();
        JComboHORA.addItem("Seleccione hora...");
    }//GEN-LAST:event_JComboElegirbarberoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new MenuCliente(emailUsuario).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCerrarApp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarApp2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro que quieres salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarApp2ActionPerformed

    private void JcalendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JcalendarioPropertyChange
        if ("calendar".equals(evt.getPropertyName())) {
        Date fecha = Jcalendario.getDate();
        if (fecha == null) return;

        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);

        // Obtener día de la semana
        String[] dias = {"", "DOMINGO", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADOS"};
        String diaSemana = dias[cal.get(Calendar.DAY_OF_WEEK)];

        String barbero = (String) JComboElegirbarbero.getSelectedItem();
        if (barbero == null || barbero.equals("Seleccione Barbero...")) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un barbero.");
            return;
        }

        // Verificar si el barbero trabaja ese día
        if (!CitaDAO.trabajaDia(barbero, diaSemana)) {
            JOptionPane.showMessageDialog(this, "El barbero " + barbero + " no trabaja los " + diaSemana.toLowerCase() + ".");
            JComboHORA.removeAllItems();
            JComboHORA.addItem("No trabaja este día");
            return;
        }

        // Obtener horarios disponibles
        List<String> horarios = CitaDAO.obtenerHorariosDisponibles(barbero, diaSemana);
        JComboHORA.removeAllItems();
        JComboHORA.addItem("Seleccione hora...");
        for (String hora : horarios) {
            JComboHORA.addItem(hora);
        }
    }

    }//GEN-LAST:event_JcalendarioPropertyChange

    /*ha sido comentado debido a cambios implementados por Ana. se ha querido dar la bienvenida a los usuarios y debido a conflictos con la variable emailUsuario, ha 
    **optado por comentar los main, un poco mas de investigacion de su parte le ha revelado que no todos lo frame deben llevar main, si no el frame principal que en este caso seria
    ** el iniciar sesion y que los frame que deben pasar por el no deberian llevar main*/
    
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarCita().setVisible(true);
            }
        });
    }   */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagendarcita;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JComboBox<String> JComboElegirbarbero;
    private javax.swing.JComboBox<String> JComboHORA;
    private javax.swing.JComboBox<String> JComboLugarcita;
    private javax.swing.JLabel JLElegirbarbero;
    private javax.swing.JLabel JLTituloAgendarcita;
    private javax.swing.JLabel JLfechadelacita;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLhora;
    private javax.swing.JLabel JLlugarcita;
    private javax.swing.JLabel JLnotasadicionales;
    private javax.swing.JLabel JLtipodeservicio;
    private javax.swing.JScrollPane JSPnotasadicionales;
    private com.toedter.calendar.JCalendar Jcalendario;
    private javax.swing.JComboBox<String> JcomboTipodeservicio;
    private javax.swing.JButton btnCerrarApp2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
