/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;

import javax.swing.JOptionPane;
import thebarbershop.utilidades.BarberoDAO;
import thebarbershop.Barbero;
import thebarbershop.utilidades.*;
import javax.swing.*;

/**
 *
 * @author Mamore e Ika
 */
public class CitasBarbero extends javax.swing.JFrame {
    private final String emailUsuario; //a esta variable le llamamos modificaciones de lugar.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CitasBarbero.class.getName());
    
    /**
     * Creates new form CitasBarbero
     * @param email
     */
    public CitasBarbero(String email) {
        this.emailUsuario = email;
        initComponents();
        setLocationRelativeTo(null);
        
        cargarCitas();
        
        // Asegurar visibilidad y habilitar menús
        jMenuOpcion.setVisible(true);
        jMiPerfil.setEnabled(true);
        jPortafolio.setEnabled(true);
        jSalir.setEnabled(true);
        jAyuda.setEnabled(true);
        jVerCitas.setEnabled(true);
    }
    
    
    private void cargarCitas() {
        // Obtener las citas del barbero desde la base de datos
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        var citas = CitaDAO.obtenerCitasPorBarbero(emailUsuario);

        if (citas.isEmpty()) {
            modeloLista.addElement("No tienes citas agendadas.");
        } else {
            for (String cita : citas) {
                modeloLista.addElement(cita);
            }
        }

        JListCitas.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListCitas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuOpcion = new javax.swing.JMenuBar();
        jVerCitas = new javax.swing.JMenu();
        jCitasVistas = new javax.swing.JMenuItem();
        jMiPerfil = new javax.swing.JMenu();
        jPerfil = new javax.swing.JMenu();
        Jperfil = new javax.swing.JMenuItem();
        jPortafolio = new javax.swing.JMenu();
        jPortafolioFoto = new javax.swing.JMenu();
        Jportafolio = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jCerrar = new javax.swing.JMenu();
        Jcerrar = new javax.swing.JMenuItem();
        jAyuda = new javax.swing.JMenu();
        jAcercaDe = new javax.swing.JMenu();
        JacercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JListCitas.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        JListCitas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JListCitas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 880, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 910, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        jMenuOpcion.setBackground(new java.awt.Color(255, 255, 255));
        jMenuOpcion.setForeground(new java.awt.Color(0, 0, 0));
        jMenuOpcion.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N

        jVerCitas.setText("Menu");

        jCitasVistas.setText("Volver al menu");
        jCitasVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCitasVistasActionPerformed(evt);
            }
        });
        jVerCitas.add(jCitasVistas);

        jMenuOpcion.add(jVerCitas);

        jMiPerfil.setText("mi perfil");
        jMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiPerfilActionPerformed(evt);
            }
        });

        jPerfil.setText("Perfil");
        jPerfil.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPerfilActionPerformed(evt);
            }
        });

        Jperfil.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        Jperfil.setLabel("Perfil");
        Jperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JperfilActionPerformed(evt);
            }
        });
        jPerfil.add(Jperfil);

        jMiPerfil.add(jPerfil);

        jMenuOpcion.add(jMiPerfil);

        jPortafolio.setText("mi portafolio");
        jPortafolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortafolioActionPerformed(evt);
            }
        });

        jPortafolioFoto.setText("portafolio de imagenes.");
        jPortafolioFoto.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jPortafolioFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPortafolioFotoActionPerformed(evt);
            }
        });

        Jportafolio.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        Jportafolio.setText("Galeria de Fotos");
        Jportafolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JportafolioActionPerformed(evt);
            }
        });
        jPortafolioFoto.add(Jportafolio);

        jPortafolio.add(jPortafolioFoto);

        jMenuOpcion.add(jPortafolio);

        jSalir.setText("salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jCerrar.setText("salir");
        jCerrar.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jCerrar.setHideActionText(true);
        jCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCerrarActionPerformed(evt);
            }
        });

        Jcerrar.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        Jcerrar.setText("Salir");
        Jcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcerrarActionPerformed(evt);
            }
        });
        jCerrar.add(Jcerrar);

        jSalir.add(jCerrar);

        jMenuOpcion.add(jSalir);

        jAyuda.setText("ayuda");

        jAcercaDe.setText("acerca de...");
        jAcercaDe.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcercaDeActionPerformed(evt);
            }
        });

        JacercaDe.setText("Acerca De");
        JacercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JacercaDeActionPerformed(evt);
            }
        });
        jAcercaDe.add(JacercaDe);

        jAyuda.add(jAcercaDe);

        jMenuOpcion.add(jAyuda);

        setJMenuBar(jMenuOpcion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAcercaDeActionPerformed

    private void JacercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JacercaDeActionPerformed
        // Configuración de la ventana AcercaDe
        AcercaDe acercaDe = new AcercaDe(this);

        // Asegurar que se cierre al perder el foco
        acercaDe.addWindowFocusListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                acercaDe.dispose();
            }
        });

        // Mostrar centrada respecto a la ventana principal
        acercaDe.setLocationRelativeTo(this);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_JacercaDeActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed

    }//GEN-LAST:event_jSalirActionPerformed

    private void jCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCerrarActionPerformed

    private void JcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcerrarActionPerformed
        // TODO add your handling code here:
        thebarbershop.utilidades.CerrarSesion.mostrarOpcionesSalida(this);
    }//GEN-LAST:event_JcerrarActionPerformed

    private void jPortafolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortafolioActionPerformed

    }//GEN-LAST:event_jPortafolioActionPerformed

    private void jPortafolioFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPortafolioFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPortafolioFotoActionPerformed

    private void JportafolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JportafolioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Proximamente...");
    }//GEN-LAST:event_JportafolioActionPerformed

    private void jMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiPerfilActionPerformed

    }//GEN-LAST:event_jMiPerfilActionPerformed

    private void jPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPerfilActionPerformed

    private void JperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JperfilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PerfilBarbero(emailUsuario).setVisible(true);
    }//GEN-LAST:event_JperfilActionPerformed

    private void jCitasVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCitasVistasActionPerformed
        // TODO add your handling code here:\
        this.dispose();
        new MenuBarbero(emailUsuario).setVisible(true);
    }//GEN-LAST:event_jCitasVistasActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new CitasBarbero().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListCitas;
    private javax.swing.JMenuItem JacercaDe;
    private javax.swing.JMenuItem Jcerrar;
    private javax.swing.JMenuItem Jperfil;
    private javax.swing.JMenuItem Jportafolio;
    private javax.swing.JMenu jAcercaDe;
    private javax.swing.JMenu jAyuda;
    private javax.swing.JMenu jCerrar;
    private javax.swing.JMenuItem jCitasVistas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuOpcion;
    private javax.swing.JMenu jMiPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPerfil;
    private javax.swing.JMenu jPortafolio;
    private javax.swing.JMenu jPortafolioFoto;
    private javax.swing.JMenu jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jVerCitas;
    // End of variables declaration//GEN-END:variables
}
