/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import javax.swing.ImageIcon;
import javax.swing.JButton;
       
/**
 *
 * @author jaelj
 */
public class IconPerfilcliente extends javax.swing.JFrame {

    private JButton botonPerfil;//referencia al boton a actualizar en el jframe anterior
//referencia al boton a actualizar en el jframe anterior
    private ImageIcon imagenSeleccionada;
    /**
     * Creates new form IconPerfil
     */ // Imagen seleccionada por el usuario
    
    public IconPerfilcliente(JButton botonPerfil) {
        this.botonPerfil = botonPerfil;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBcliente1 = new javax.swing.JButton();
        JBcliente2 = new javax.swing.JButton();
        JBcliente3 = new javax.swing.JButton();
        JBbarbero1 = new javax.swing.JButton();
        JBbarbero2 = new javax.swing.JButton();
        JBbarbero3 = new javax.swing.JButton();
        JLguardar = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBcliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cliente1.png"))); // NOI18N
        JBcliente1.setText("jButton1");
        JBcliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(JBcliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 190));

        JBcliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cliente2.png"))); // NOI18N
        JBcliente2.setText("jButton2");
        JBcliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcliente2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBcliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 180, 190));

        JBcliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cliente3.png"))); // NOI18N
        JBcliente3.setText("jButton1");
        JBcliente3.setPreferredSize(new java.awt.Dimension(180, 190));
        JBcliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcliente3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBcliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 180, 190));

        JBbarbero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Barbero1.png"))); // NOI18N
        JBbarbero1.setText("jButton1");
        JBbarbero1.setPreferredSize(new java.awt.Dimension(180, 190));
        JBbarbero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbarbero1ActionPerformed(evt);
            }
        });
        getContentPane().add(JBbarbero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 180, 190));

        JBbarbero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Barbero2.png"))); // NOI18N
        JBbarbero2.setText("jButton1");
        JBbarbero2.setPreferredSize(new java.awt.Dimension(180, 190));
        JBbarbero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbarbero2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBbarbero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 180, 190));

        JBbarbero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/barbero3.png"))); // NOI18N
        JBbarbero3.setText("jButton1");
        JBbarbero3.setPreferredSize(new java.awt.Dimension(180, 190));
        JBbarbero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbarbero3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBbarbero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 180, 190));

        JLguardar.setBackground(new java.awt.Color(13, 73, 11));
        JLguardar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLguardar.setText("Guardar");
        JLguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLguardarActionPerformed(evt);
            }
        });
        getContentPane().add(JLguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 150, 70));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/fondoIcono.png"))); // NOI18N
        JLfondo.setText("jLabel1");
        getContentPane().add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBcliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcliente1ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/Cliente1.png"));
    }//GEN-LAST:event_JBcliente1ActionPerformed

    private void JBcliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcliente2ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/cliente2.png"));
    }//GEN-LAST:event_JBcliente2ActionPerformed

    private void JBcliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcliente3ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/Cliente3.png"));
    }//GEN-LAST:event_JBcliente3ActionPerformed

    private void JBbarbero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbarbero1ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/Barbero1.png"));
    }//GEN-LAST:event_JBbarbero1ActionPerformed

    private void JBbarbero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbarbero2ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/Barbero2.png"));
    }//GEN-LAST:event_JBbarbero2ActionPerformed

    private void JBbarbero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbarbero3ActionPerformed
        // TODO add your handling code here:
        imagenSeleccionada = new ImageIcon(getClass().getResource("/com/images/barbero3.png"));
    }//GEN-LAST:event_JBbarbero3ActionPerformed

    private void JLguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLguardarActionPerformed
       if (imagenSeleccionada != null && botonPerfil !=null){ 
          botonPerfil.setIcon(imagenSeleccionada);
          botonPerfil.setText("");
        }
       this.dispose();
    }//GEN-LAST:event_JLguardarActionPerformed

    //
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbarbero1;
    private javax.swing.JButton JBbarbero2;
    private javax.swing.JButton JBbarbero3;
    private javax.swing.JButton JBcliente1;
    private javax.swing.JButton JBcliente2;
    private javax.swing.JButton JBcliente3;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JButton JLguardar;
    // End of variables declaration//GEN-END:variables
}
