/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import javax.swing.JOptionPane;

/**
 *
 * @author jaelj
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        JPprincipal = new javax.swing.JPanel();
        JLiconoBarberia = new javax.swing.JLabel();
        JLTitleIniciarsesion = new javax.swing.JLabel();
        JLcorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        JScorreo = new javax.swing.JSeparator();
        JLcontraseña = new javax.swing.JLabel();
        JPcontraseña = new javax.swing.JPasswordField();
        sprContrasena = new javax.swing.JSeparator();
        btnEntrar = new javax.swing.JButton();
        lblRegistrate = new javax.swing.JLabel();
        JLimagenBarberia = new javax.swing.JLabel();
        JLempresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Iniciar Sesion");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPprincipal.setBackground(new java.awt.Color(255, 255, 255));
        JPprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLiconoBarberia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLiconoBarberia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png"))); // NOI18N
        JPprincipal.add(JLiconoBarberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, 70));
        JLiconoBarberia.getAccessibleContext().setAccessibleDescription("");

        JLTitleIniciarsesion.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        JLTitleIniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        JLTitleIniciarsesion.setText("INICIA SESIÓN");
        JPprincipal.add(JLTitleIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        JLcorreo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLcorreo.setForeground(new java.awt.Color(0, 0, 0));
        JLcorreo.setText("Correo");
        JPprincipal.add(JLcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        JPprincipal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 490, 30));
        JPprincipal.add(JScorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 510, 20));

        JLcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        JLcontraseña.setText("CONTRASEÑA");
        JPprincipal.add(JLcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        JPcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        JPcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JPcontraseña.setToolTipText("");
        JPcontraseña.setBorder(null);
        JPcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPcontraseñaActionPerformed(evt);
            }
        });
        JPprincipal.add(JPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 490, 30));
        JPprincipal.add(sprContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 510, 20));

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        JPprincipal.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 40));

        lblRegistrate.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        lblRegistrate.setForeground(new java.awt.Color(0, 102, 204));
        lblRegistrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrate.setText("Registrate");
        lblRegistrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrateMouseClicked(evt);
            }
        });
        JPprincipal.add(lblRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 40));

        JLimagenBarberia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen3(1).jpg"))); // NOI18N
        JPprincipal.add(JLimagenBarberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 330, 500));

        JLempresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLempresa.setForeground(new java.awt.Color(0, 0, 0));
        JLempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLempresa.setText("© Propiedad de Ancharja Studios ");
        JPprincipal.add(JLempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 290, 20));

        getContentPane().add(JPprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));
        JPprincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void JPcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPcontraseñaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
      
        String email = txtCorreo.getText();
        String password = new String(JPcontraseña.getPassword());
        // Validar que los campos no están vacíos
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El email es obligatorio");
            return;
            
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña es obligatoria");
            return;
        }

        // Validar formato de email
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Ingrese un email valido");
            return;
        }

        // Validar contraseña mínimo 8 caracteres
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener minimo 8 caracteres");
            return;
        }

        // Si pasa todas las validaciones, ir al menú
//        System.out.println("Login exitoso para: " + email);
        this.dispose();
        new MenuCliente().setVisible(true);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblRegistrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrateMouseClicked
        // Cerrar esta ventana
        this.dispose();

        // Abrir ventana de registro
        new RegistroCliente().setVisible(true);
    }//GEN-LAST:event_lblRegistrateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLTitleIniciarsesion;
    private javax.swing.JLabel JLcontraseña;
    private javax.swing.JLabel JLcorreo;
    private javax.swing.JLabel JLempresa;
    private javax.swing.JLabel JLiconoBarberia;
    private javax.swing.JLabel JLimagenBarberia;
    private javax.swing.JPasswordField JPcontraseña;
    private javax.swing.JPanel JPprincipal;
    private javax.swing.JSeparator JScorreo;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRegistrate;
    private javax.swing.JSeparator sprContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
