/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import javax.swing.JOptionPane;
import thebarbershop.utilidades.BarberoDAO;
import thebarbershop.Barbero;
import thebarbershop.utilidades.*;
import javax.swing.*;
/**
 *
 * @author jaelj
 */
public class MenuBarbero extends javax.swing.JFrame {
    private final String emailUsuario; //a esta variable le llamamos modificaciones de lugar.


    /**
     * Creates new form MenuBarbero
     * @param email
     */
    public MenuBarbero(String email) {
        this.emailUsuario = email;
        initComponents();
         setLocationRelativeTo(null);
        cargarDatosIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLtitulo = new javax.swing.JLabel();
        iconBarber = new javax.swing.JLabel();
        btnCerrarApp = new javax.swing.JButton();
        IconBarber2 = new javax.swing.JLabel();
        JLresumendeactividad = new javax.swing.JLabel();
        JSPresumenActividad = new javax.swing.JScrollPane();
        JLestilosdisp = new javax.swing.JLabel();
        JComboEstilosdisp = new javax.swing.JComboBox<>();
        JLicono = new javax.swing.JLabel();
        JLhorarios = new javax.swing.JLabel();
        JcomboHorarios = new javax.swing.JComboBox<>();
        btnPortafolio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Panel Barbero ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLtitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtitulo.setText("NOMBRE BARBERIA");
        jPanel1.add(JLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 520, 50));

        iconBarber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png"))); // NOI18N
        jPanel1.add(iconBarber, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 60, 70));

        btnCerrarApp.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarApp.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        btnCerrarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/apagar.png"))); // NOI18N
        btnCerrarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarAppActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 40, -1));

        IconBarber2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png"))); // NOI18N
        jPanel1.add(IconBarber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        JLresumendeactividad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLresumendeactividad.setForeground(new java.awt.Color(255, 255, 255));
        JLresumendeactividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLresumendeactividad.setText("Resumen de Actividad:");
        jPanel1.add(JLresumendeactividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 240, 30));
        jPanel1.add(JSPresumenActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 320, 240));

        JLestilosdisp.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLestilosdisp.setForeground(new java.awt.Color(255, 255, 255));
        JLestilosdisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLestilosdisp.setText("Estilos disponibles:");
        jPanel1.add(JLestilosdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, 30));

        JComboEstilosdisp.setBackground(new java.awt.Color(51, 51, 51));
        JComboEstilosdisp.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JComboEstilosdisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar estilos....", "Taper Fade", "Low Fade", "Mid Fade", "High Fade", "Skin Fade", "Drop Fade" }));
        JComboEstilosdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboEstilosdispActionPerformed(evt);
            }
        });
        jPanel1.add(JComboEstilosdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, 60));

        JLicono.setText("jLabel3");
        jPanel1.add(JLicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, 130));

        JLhorarios.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLhorarios.setForeground(new java.awt.Color(255, 255, 255));
        JLhorarios.setText("Horarios disponibles");
        jPanel1.add(JLhorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 230, 30));

        JcomboHorarios.setBackground(new java.awt.Color(51, 51, 51));
        JcomboHorarios.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JcomboHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregue horarios..." }));
        JcomboHorarios.setPreferredSize(new java.awt.Dimension(180, 23));
        jPanel1.add(JcomboHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 230, 60));

        btnPortafolio.setBackground(new java.awt.Color(153, 153, 153));
        btnPortafolio.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnPortafolio.setForeground(new java.awt.Color(51, 51, 51));
        btnPortafolio.setText("Mi Portafolio de Fotos");
        btnPortafolio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPortafolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortafolioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPortafolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 190, 60));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Mi informacion de Barbero");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 230, 50));

        JBguardar.setBackground(new java.awt.Color(13, 73, 11));
        JBguardar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBguardar.setForeground(new java.awt.Color(255, 255, 255));
        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 210, 50));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        jPanel1.add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new PerfilBarbero(emailUsuario).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPortafolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortafolioActionPerformed
      JOptionPane.showMessageDialog(this, "Proximamente...");       
    }//GEN-LAST:event_btnPortafolioActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
    if (!validarCampos()) return;

        String nombreBarberia = JLtitulo.getText().trim();
        EstiloCorteDAO.Estilo estilo = (EstiloCorteDAO.Estilo) JComboEstilosdisp.getSelectedItem();
        DisponibilidadDAO.Horario horario = (DisponibilidadDAO.Horario) JcomboHorarios.getSelectedItem();

        boolean ok = true;

        // 1. Actualizar nombre barbería
        if (!BarberoDAO.actualizarNombreBarberia(emailUsuario, nombreBarberia)) {
            ok = false;
        }
        

        // 2. Actualizar especialidades
        if (estilo != null && !estilo.toString().startsWith("Agregar")) {
            if (!BarberoDAO.actualizarEspecialidades(emailUsuario, estilo.toString())) {
                ok = false;
            }
        }

        JOptionPane.showMessageDialog(this,
            ok ? "Datos guardados correctamente." : "Error al guardar algunos datos.");
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JComboEstilosdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboEstilosdispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboEstilosdispActionPerformed

    private void btnCerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarAppActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro que quieres salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarAppActionPerformed
    private void cargarDatosIniciales() {
        Barbero barbero = BarberoDAO.obtenerBarberoPorEmail(emailUsuario);
        if (barbero != null) {
            JLtitulo.setText(barbero.getNombreBarberia());
            cargarEstilosDisponibles();
            cargarHorariosDisponibles();
            mostrarResumenActividad();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron datos del barbero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarEstilosDisponibles() {
        JComboEstilosdisp.removeAllItems();
        JComboEstilosdisp.addItem("Agregar estilos...");

        for (EstiloCorteDAO.Estilo estilo : EstiloCorteDAO.obtenerEstilos()) {
            JComboEstilosdisp.addItem(estilo.toString());
        }
    }

    private void cargarHorariosDisponibles() {
        int idPeluquero = BarberoDAO.obtenerIdPeluquero(emailUsuario);
        if (idPeluquero == 0) return;

        JcomboHorarios.removeAllItems();
        JcomboHorarios.addItem("Agregue horarios...");

        for (DisponibilidadDAO.Horario horario : DisponibilidadDAO.obtenerHorarios(idPeluquero)) {
            JcomboHorarios.addItem(horario.toString());
        }
    }

    private void mostrarResumenActividad() {
        int idPeluquero = BarberoDAO.obtenerIdPeluquero(emailUsuario);
        ResumenDAO.Resumen resumen = ResumenDAO.obtenerResumen(idPeluquero);

        JTextArea area = new JTextArea();
        area.setText("Total de citas realizadas: " + resumen.totalCitas + "\n" +
                    "Ingresos totales: $" + String.format("%.2f", resumen.totalIngresos));
        area.setEditable(false);
        JSPresumenActividad.setViewportView(area);
    }

    private boolean validarCampos() {
        if (JLtitulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre de barbería es obligatorio.");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    
    /*ha sido comentado debido a cambios implementados por Ana. se ha querido dar la bienvenida a los usuarios y debido a conflictos con la variable emailUsuario, ha 
    **optado por comentar los main, un poco mas de investigacion de su parte le ha revelado que no todos lo frame deben llevar main, si no el frame principal que en este caso seria
    ** el iniciar sesion y que los frame que deben pasar por el no deberian llevar main*/
    
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBarbero().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconBarber2;
    private javax.swing.JButton JBguardar;
    private javax.swing.JComboBox<String> JComboEstilosdisp;
    private javax.swing.JLabel JLestilosdisp;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLhorarios;
    private javax.swing.JLabel JLicono;
    private javax.swing.JLabel JLresumendeactividad;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JScrollPane JSPresumenActividad;
    private javax.swing.JComboBox<String> JcomboHorarios;
    private javax.swing.JButton btnCerrarApp;
    private javax.swing.JButton btnPortafolio;
    private javax.swing.JLabel iconBarber;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
