/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;

import thebarbershop.Jframe.MenuBarbero;
import thebarbershop.Jframe.IniciarSesion;
import thebarbershop.Jframe.AgendarCita;

/**
 *
 * @author jaelj
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        JPusuario = new javax.swing.JPanel();
        JLBienvenido = new javax.swing.JLabel();
        JLiconoUser = new javax.swing.JLabel();
        JBperfil = new javax.swing.JButton();
        JBagendarcita = new javax.swing.JButton();
        JBcerrarsesion = new javax.swing.JButton();
        JPmenu = new javax.swing.JPanel();
        JBtitle = new javax.swing.JLabel();
        JBseleccioneopcion = new javax.swing.JLabel();
        JBcitasagendadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBeslogan = new javax.swing.JLabel();
        JBimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Menu Principal ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPusuario.setBackground(new java.awt.Color(51, 51, 51));
        JPusuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBienvenido.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        JLBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBienvenido.setText("BIENVENIDO");
        JPusuario.add(JLBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 20, 140, -1));

        JLiconoUser.setBackground(new java.awt.Color(255, 255, 255));
        JLiconoUser.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLiconoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLiconoUser.setText("ICON");
        JPusuario.add(JLiconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 130));

        JBperfil.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBperfil.setText("Mi Pefil");
        JBperfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBperfilActionPerformed(evt);
            }
        });
        JPusuario.add(JBperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, -1));

        JBagendarcita.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBagendarcita.setText("Agendar Cita");
        JBagendarcita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBagendarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagendarcitaActionPerformed(evt);
            }
        });
        JPusuario.add(JBagendarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        JBcerrarsesion.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBcerrarsesion.setText("Cerrar Sesion ");
        JBcerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcerrarsesionActionPerformed(evt);
            }
        });
        JPusuario.add(JBcerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, -1));

        getContentPane().add(JPusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 510));

        JPmenu.setBackground(new java.awt.Color(255, 255, 255));
        JPmenu.setPreferredSize(new java.awt.Dimension(800, 600));
        JPmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtitle.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        JBtitle.setForeground(new java.awt.Color(0, 0, 0));
        JBtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBtitle.setText("T.B.S");
        JPmenu.add(JBtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, -1));

        JBseleccioneopcion.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBseleccioneopcion.setForeground(new java.awt.Color(0, 0, 0));
        JBseleccioneopcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBseleccioneopcion.setText("Seleccione una opcion del menu lateral");
        JBseleccioneopcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPmenu.add(JBseleccioneopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 30));

        JBcitasagendadas.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBcitasagendadas.setForeground(new java.awt.Color(0, 0, 0));
        JBcitasagendadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBcitasagendadas.setText("MIS CITAS AGENDADAS:");
        JBcitasagendadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPmenu.add(JBcitasagendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("NO HAY CITAS AGENDADAS");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        JPmenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, 200));

        JBeslogan.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JBeslogan.setForeground(new java.awt.Color(0, 0, 0));
        JBeslogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBeslogan.setText("TheBarberShop - Tus barerias de confianza");
        JPmenu.add(JBeslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 360, 20));

        JBimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/fashion-8254063_1280.jpg"))); // NOI18N
        JBimagen.setText("jLabel7");
        JPmenu.add(JBimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 310, 510));

        getContentPane().add(JPmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 720, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBagendarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagendarcitaActionPerformed
        this.dispose();
        new AgendarCita().setVisible(true);
    }//GEN-LAST:event_JBagendarcitaActionPerformed

    private void JBperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBperfilActionPerformed
        this.dispose();
        new PerfilCliente().setVisible(true);
    }//GEN-LAST:event_JBperfilActionPerformed

    private void JBcerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcerrarsesionActionPerformed
        this.dispose();
        new IniciarSesion().setVisible(true);
    }//GEN-LAST:event_JBcerrarsesionActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagendarcita;
    private javax.swing.JButton JBcerrarsesion;
    private javax.swing.JLabel JBcitasagendadas;
    private javax.swing.JLabel JBeslogan;
    private javax.swing.JLabel JBimagen;
    private javax.swing.JButton JBperfil;
    private javax.swing.JLabel JBseleccioneopcion;
    private javax.swing.JLabel JBtitle;
    private javax.swing.JLabel JLBienvenido;
    private javax.swing.JLabel JLiconoUser;
    private javax.swing.JPanel JPmenu;
    private javax.swing.JPanel JPusuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
