/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;

import thebarbershop.Jframe.MenuCliente;

/**
 *
 * @author jaelj
 */
public class PerfilCliente extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public PerfilCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JLtitulo = new javax.swing.JLabel();
        JLfotoperfil = new javax.swing.JLabel();
        JBicono = new javax.swing.JButton();
        JBciudad = new javax.swing.JLabel();
        JCOMBOciudad = new javax.swing.JComboBox<>();
        JLnombre = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JLcorreo = new javax.swing.JLabel();
        JTcorreo = new javax.swing.JTextField();
        JLtelefono = new javax.swing.JLabel();
        JFtelefono = new javax.swing.JFormattedTextField();
        JLcontraseña = new javax.swing.JLabel();
        JPcontraseña = new javax.swing.JPasswordField();
        JBguardar = new javax.swing.JButton();
        JBvolveralmenu = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Mi Perfil");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(920, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLtitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        JLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtitulo.setText("Mi Perfil");
        jPanel1.add(JLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 340, 60));

        JLfotoperfil.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLfotoperfil.setText("Foto de perfil");
        jPanel1.add(JLfotoperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        JBicono.setText("jButton3");
        JBicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBiconoActionPerformed(evt);
            }
        });
        jPanel1.add(JBicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 140));

        JBciudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBciudad.setText("Ciudad");
        jPanel1.add(JBciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 190, 30));

        JCOMBOciudad.setBackground(new java.awt.Color(51, 51, 51));
        JCOMBOciudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JCOMBOciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Santo Domingo", "Santiago", "San Cristóbal", "San Pedro de Macorís" }));
        jPanel1.add(JCOMBOciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 200, 50));

        JLnombre.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnombre.setText("Nombre");
        jPanel1.add(JLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 180, 30));

        JTnombre.setBackground(new java.awt.Color(135, 135, 135));
        JTnombre.setForeground(new java.awt.Color(255, 255, 255));
        JTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 240, 50));

        JLcorreo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLcorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcorreo.setText("Correo");
        jPanel1.add(JLcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 240, 30));

        JTcorreo.setBackground(new java.awt.Color(135, 135, 135));
        JTcorreo.setForeground(new java.awt.Color(255, 255, 255));
        JTcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(JTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 240, 50));

        JLtelefono.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtelefono.setText("Telefono");
        jPanel1.add(JLtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 240, 30));

        JFtelefono.setBackground(new java.awt.Color(135, 135, 135));
        try {
            JFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(JFtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 240, 50));

        JLcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcontraseña.setText("Contraseña");
        jPanel1.add(JLcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 240, 30));

        JPcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        JPcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(JPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 240, 50));

        JBguardar.setBackground(new java.awt.Color(13, 73, 11));
        JBguardar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JBguardar.setForeground(new java.awt.Color(255, 255, 255));
        JBguardar.setText("Guardar Cambios");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 220, 50));

        JBvolveralmenu.setBackground(new java.awt.Color(153, 153, 153));
        JBvolveralmenu.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBvolveralmenu.setForeground(new java.awt.Color(255, 255, 255));
        JBvolveralmenu.setText("Volver al Menu");
        JBvolveralmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvolveralmenuActionPerformed(evt);
            }
        });
        jPanel1.add(JBvolveralmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 220, 50));

        JLfondo.setText("fondo");
        jPanel1.add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcorreoActionPerformed

    private void JBvolveralmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvolveralmenuActionPerformed
        this.dispose();
        new MenuCliente().setVisible(true);
    }//GEN-LAST:event_JBvolveralmenuActionPerformed

    private void JBiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBiconoActionPerformed
        // TODO add your handling code here:
                IconPerfilcliente selector = new IconPerfilcliente(JBicono);
        selector.setVisible(true);
    }//GEN-LAST:event_JBiconoActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBciudad;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBicono;
    private javax.swing.JButton JBvolveralmenu;
    private javax.swing.JComboBox<String> JCOMBOciudad;
    private javax.swing.JFormattedTextField JFtelefono;
    private javax.swing.JLabel JLcontraseña;
    private javax.swing.JLabel JLcorreo;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLfotoperfil;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JPasswordField JPcontraseña;
    private javax.swing.JTextField JTcorreo;
    private javax.swing.JTextField JTnombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
