/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;

import javax.swing.JOptionPane;
import thebarbershop.Barbero;
import thebarbershop.utilidades.ConsultaNombreBarberia;
import thebarbershop.utilidades.BarberoDAO;
import thebarbershop.utilidades.Validaciones;
import thebarbershop.utilidades.Seguridad;
/**
 *
 * @author jaelj
 */
public class PerfilBarbero extends javax.swing.JFrame {
    private final String emailUsuario;
    /**
     * Creates new form PerfilBarbero
     * @param email
     */
    public PerfilBarbero(String email) {
        this.emailUsuario = email;
        initComponents();
         setLocationRelativeTo(null);
        cargarDatosPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLtitulo = new javax.swing.JLabel();
        icono2 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        JLfotodeperfil = new javax.swing.JLabel();
        JLnombreBarberia = new javax.swing.JLabel();
        JBicono = new javax.swing.JButton();
        JLnombre = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JBCerrarSesion = new javax.swing.JButton();
        JBeliminarPerfil = new javax.swing.JButton();
        JLtelefono = new javax.swing.JLabel();
        JFtelefono = new javax.swing.JFormattedTextField();
        JLcontraseña = new javax.swing.JLabel();
        JPcontraseña = new javax.swing.JPasswordField();
        JLcorreo = new javax.swing.JLabel();
        JTcorreo = new javax.swing.JTextField();
        JLciudad = new javax.swing.JLabel();
        JComboCiudad = new javax.swing.JComboBox<>();
        JLexperiencia = new javax.swing.JLabel();
        JcomboExperiencia = new javax.swing.JComboBox<>();
        JLguardar = new javax.swing.JButton();
        JLvolveralmenu = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLtitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtitulo.setText("Mi Perfil");
        getContentPane().add(JLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 340, 60));

        icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png"))); // NOI18N
        getContentPane().add(icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 70));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/peluqueria(1).png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 60, 70));

        JLfotodeperfil.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLfotodeperfil.setForeground(new java.awt.Color(255, 255, 255));
        JLfotodeperfil.setText("Foto de perfil");
        getContentPane().add(JLfotodeperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        JLnombreBarberia.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLnombreBarberia.setForeground(new java.awt.Color(255, 255, 255));
        JLnombreBarberia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnombreBarberia.setText("Barberia");
        getContentPane().add(JLnombreBarberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 370, 30));

        JBicono.setText("ICON");
        JBicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBiconoActionPerformed(evt);
            }
        });
        getContentPane().add(JBicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 140));

        JLnombre.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLnombre.setForeground(new java.awt.Color(255, 255, 255));
        JLnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnombre.setText("Nombre");
        getContentPane().add(JLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 180, 30));

        JTnombre.setBackground(new java.awt.Color(153, 153, 153));
        JTnombre.setForeground(new java.awt.Color(0, 0, 0));
        JTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 240, 50));

        JBCerrarSesion.setBackground(new java.awt.Color(153, 0, 51));
        JBCerrarSesion.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JBCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        JBCerrarSesion.setText("Salir del Perfil");
        JBCerrarSesion.setActionCommand("Cerrar Sesion");
        JBCerrarSesion.setPreferredSize(new java.awt.Dimension(175, 24));
        JBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(JBCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 200, 50));

        JBeliminarPerfil.setBackground(new java.awt.Color(153, 0, 51));
        JBeliminarPerfil.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JBeliminarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        JBeliminarPerfil.setText("Eliminar Perfil");
        JBeliminarPerfil.setPreferredSize(new java.awt.Dimension(175, 24));
        JBeliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(JBeliminarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 200, 50));

        JLtelefono.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtelefono.setForeground(new java.awt.Color(255, 255, 255));
        JLtelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtelefono.setText("Telefono");
        getContentPane().add(JLtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 240, 30));

        JFtelefono.setBackground(new java.awt.Color(153, 153, 153));
        JFtelefono.setForeground(new java.awt.Color(0, 0, 0));
        try {
            JFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(JFtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 240, 50));

        JLcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        JLcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcontraseña.setText("Contraseña");
        getContentPane().add(JLcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 240, 30));

        JPcontraseña.setBackground(new java.awt.Color(153, 153, 153));
        JPcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(JPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 240, 50));

        JLcorreo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLcorreo.setForeground(new java.awt.Color(255, 255, 255));
        JLcorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcorreo.setText("Correo");
        getContentPane().add(JLcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 240, 30));

        JTcorreo.setBackground(new java.awt.Color(153, 153, 153));
        JTcorreo.setForeground(new java.awt.Color(0, 0, 0));
        JTcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcorreoActionPerformed(evt);
            }
        });
        getContentPane().add(JTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 240, 50));

        JLciudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLciudad.setForeground(new java.awt.Color(255, 255, 255));
        JLciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLciudad.setText("Ciudad");
        getContentPane().add(JLciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 30));

        JComboCiudad.setBackground(new java.awt.Color(51, 51, 51));
        JComboCiudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JComboCiudad.setForeground(new java.awt.Color(255, 255, 255));
        JComboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Santo Domingo", "Santiago", "San Cristóbal", "San Pedro de Macorís" }));
        getContentPane().add(JComboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, 50));

        JLexperiencia.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLexperiencia.setForeground(new java.awt.Color(255, 255, 255));
        JLexperiencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLexperiencia.setText("Experiencia");
        getContentPane().add(JLexperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 200, 30));

        JcomboExperiencia.setBackground(new java.awt.Color(51, 51, 51));
        JcomboExperiencia.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JcomboExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        JcomboExperiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "1 - 6 MESES", "6 - 12 MESES", "1 - 2 AÑOS", "2 - 4 AÑOS", "4 - 8 AÑOS", "8 o MÁS" }));
        getContentPane().add(JcomboExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 200, 50));

        JLguardar.setBackground(new java.awt.Color(13, 73, 11));
        JLguardar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        JLguardar.setForeground(new java.awt.Color(255, 255, 255));
        JLguardar.setText("Guardar Cambios");
        JLguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLguardarActionPerformed(evt);
            }
        });
        getContentPane().add(JLguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 200, 50));

        JLvolveralmenu.setBackground(new java.awt.Color(153, 153, 153));
        JLvolveralmenu.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLvolveralmenu.setForeground(new java.awt.Color(51, 51, 51));
        JLvolveralmenu.setText("Volver al Menu");
        JLvolveralmenu.setPreferredSize(new java.awt.Dimension(175, 24));
        JLvolveralmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLvolveralmenuActionPerformed(evt);
            }
        });
        getContentPane().add(JLvolveralmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 200, 50));

        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        getContentPane().add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLvolveralmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLvolveralmenuActionPerformed
        this.dispose();
        new MenuBarbero(emailUsuario).setVisible(true);
    }//GEN-LAST:event_JLvolveralmenuActionPerformed

    private void JTcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcorreoActionPerformed

    private void JBiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBiconoActionPerformed
        // TODO add your handling code here:
        IconPerfilcliente selector = new IconPerfilcliente(JBicono);
        selector.setVisible(true);
    }//GEN-LAST:event_JBiconoActionPerformed

    private void JBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCerrarSesionActionPerformed
        thebarbershop.utilidades.CerrarSesion.mostrarOpcionesSalida(this);
    }//GEN-LAST:event_JBCerrarSesionActionPerformed

    private void JBeliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarPerfilActionPerformed
        thebarbershop.utilidades.EliminarPerfil.eliminarPerfilCliente(this, emailUsuario);
    }//GEN-LAST:event_JBeliminarPerfilActionPerformed

    private void JLguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLguardarActionPerformed
        // Validaciones
        if (!Validaciones.validarNombre(JTnombre)) return;
        if (!Validaciones.validarTelefono(JFtelefono.getText())) return;
        if (!Validaciones.validarCiudad(JComboCiudad)) return;
        if (!Validaciones.validarYearExperiencia(JcomboExperiencia)) return;

        String nombre = JTnombre.getText().trim();
        String correo = JTcorreo.getText().trim();
        String telefono = JFtelefono.getText().replaceAll("[^0-9]", "");
        String ciudad = (String) JComboCiudad.getSelectedItem();
        String seleccion = (String) JcomboExperiencia.getSelectedItem();
        int experiencia = comboAExperiencia(seleccion); // Asegúrate de que no sea 0 si es válido

        if (experiencia == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una experiencia válida.");
            return;
        }

        if (!correo.equals(emailUsuario)) {
            JOptionPane.showMessageDialog(this, "No se puede cambiar el correo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Contraseña
        String contrasena = new String(JPcontraseña.getPassword()).trim();
        String contrasenaEncriptada = null;
        if (!contrasena.isEmpty()) {
            if (!Validaciones.validarContraseña(JPcontraseña)) return;
            contrasenaEncriptada = Seguridad.encriptarContraseña(contrasena);
        }

        // Crear objeto
        Barbero barbero = new Barbero(
            nombre, correo, ciudad, telefono, 
            contrasenaEncriptada != null ? contrasenaEncriptada : "", 
            experiencia, 
            "Nombre por defecto" // o obtén de otro campo si lo tienes
        );

        // Guardar
        if (BarberoDAO.actualizarBarbero(barbero)) {
            JOptionPane.showMessageDialog(this, "Perfil actualizado.");
            JPcontraseña.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el perfil.");
        }
    }//GEN-LAST:event_JLguardarActionPerformed

    private void cargarDatosPerfil() {
        Barbero barbero = BarberoDAO.obtenerBarberoPorEmail(emailUsuario);
        if (barbero != null) {
            JTnombre.setText(barbero.getNombre());
            JTcorreo.setText(barbero.getEmail());
            JFtelefono.setText(barbero.getTelefono());
            JComboCiudad.setSelectedItem(barbero.getCiudad());

            //Manejar experiencia 0 o no válida
            String experienciaTexto = experienciaACombo(barbero.getExperiencia());
            JcomboExperiencia.setSelectedItem(experienciaTexto);

            // Nombre de la barbería
            String nombreBarberia = ConsultaNombreBarberia.obtenerNombreBarberia(emailUsuario);
            JLnombreBarberia.setText(nombreBarberia.isEmpty() ? "Barbería no asignada" : nombreBarberia);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron datos del barbero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Convierte texto del combo a número
    private int comboAExperiencia(String seleccion) {
    switch (seleccion) {
        case "1 - 6 MESES":     return 1;
        case "6 - 12 MESES":    return 2;
        case "1 - 2 AÑOS":      return 3;
        case "2 - 4 AÑOS":      return 4;
        case "4 - 8 AÑOS":      return 5;
        case "8 o MÁS":         return 6;
        default:                return 0;
    }
}

    // Convierte número a texto del combo
    private String experienciaACombo(int valor) {
        switch (valor) {
            case 1: return "1 - 6 MESES";
            case 2: return "6 - 12 MESES";
            case 3: return "1 - 2 AÑOS";
            case 4: return "2 - 4 AÑOS";
            case 5: return "4 - 8 AÑOS";
            case 6: return "8 o MÁS";
            default: return "Seleccione....";
        }
    }
    /**
     * @param args the command line arguments
     */
    /*ha sido comentado debido a cambios implementados por Ana. se ha querido dar la bienvenida a los usuarios y debido a conflictos con la variable emailUsuario, ha 
    **optado por comentar los main, un poco mas de investigacion de su parte le ha revelado que no todos lo frame deben llevar main, si no el frame principal que en este caso seria
    ** el iniciar sesion y que los frame que deben pasar por el no deberian llevar main*/
    
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilBarbero().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCerrarSesion;
    private javax.swing.JButton JBeliminarPerfil;
    private javax.swing.JButton JBicono;
    private javax.swing.JComboBox<String> JComboCiudad;
    private javax.swing.JFormattedTextField JFtelefono;
    private javax.swing.JLabel JLciudad;
    private javax.swing.JLabel JLcontraseña;
    private javax.swing.JLabel JLcorreo;
    private javax.swing.JLabel JLexperiencia;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLfotodeperfil;
    private javax.swing.JButton JLguardar;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLnombreBarberia;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JButton JLvolveralmenu;
    private javax.swing.JPasswordField JPcontraseña;
    private javax.swing.JTextField JTcorreo;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JComboBox<String> JcomboExperiencia;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono2;
    // End of variables declaration//GEN-END:variables
}
