/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thebarbershop.Jframe;
import thebarbershop.utilidades.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jaelj
 */
public class RegistroBarbero extends javax.swing.JFrame {

    /**
     * Creates new form RegistroBarbero
     */
    public RegistroBarbero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        JLtitleRegistroBarbe = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JLemail = new javax.swing.JLabel();
        JTemail = new javax.swing.JTextField();
        JLtelefono = new javax.swing.JLabel();
        JFtelefono = new javax.swing.JFormattedTextField();
        JLtipouser = new javax.swing.JLabel();
        Cliente = new javax.swing.JRadioButton();
        Barbero = new javax.swing.JRadioButton();
        JLciudad = new javax.swing.JLabel();
        JcomboCiudad = new javax.swing.JComboBox<>();
        JLexperiencia = new javax.swing.JLabel();
        JcomboExperiencia = new javax.swing.JComboBox<>();
        JLcontraseña = new javax.swing.JLabel();
        JPcontraseña = new javax.swing.JPasswordField();
        JPRegistrarse = new javax.swing.JButton();
        JPvolver = new javax.swing.JButton();
        JLfondo = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(935, 535));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLtitleRegistroBarbe.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        JLtitleRegistroBarbe.setForeground(new java.awt.Color(255, 255, 255));
        JLtitleRegistroBarbe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtitleRegistroBarbe.setText("Registro de Barbero");
        getContentPane().add(JLtitleRegistroBarbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 640, 50));

        Nombre.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        JTnombre.setBackground(new java.awt.Color(204, 204, 204));
        JTnombre.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JTnombre.setForeground(new java.awt.Color(0, 0, 0));
        JTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTnombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnombreActionPerformed(evt);
            }
        });
        getContentPane().add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 270, 50));

        JLemail.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLemail.setForeground(new java.awt.Color(255, 255, 255));
        JLemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLemail.setText("Email:");
        getContentPane().add(JLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        JTemail.setBackground(new java.awt.Color(204, 204, 204));
        JTemail.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JTemail.setForeground(new java.awt.Color(0, 0, 0));
        JTemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTemailActionPerformed(evt);
            }
        });
        getContentPane().add(JTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 270, 50));

        JLtelefono.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtelefono.setForeground(new java.awt.Color(255, 255, 255));
        JLtelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtelefono.setText("Telefono:");
        getContentPane().add(JLtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 110, 30));

        JFtelefono.setBackground(new java.awt.Color(204, 204, 204));
        JFtelefono.setForeground(new java.awt.Color(0, 0, 0));
        try {
            JFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(JFtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 270, 50));

        JLtipouser.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtipouser.setForeground(new java.awt.Color(255, 255, 255));
        JLtipouser.setText("Tipo de Usuario:");
        getContentPane().add(JLtipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 30));

        buttonGroup1.add(Cliente);
        Cliente.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Usuario");
        Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 80, 30));

        buttonGroup1.add(Barbero);
        Barbero.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        Barbero.setForeground(new java.awt.Color(255, 255, 255));
        Barbero.setSelected(true);
        Barbero.setText("Barbero");
        Barbero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Barbero.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Barbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarberoActionPerformed(evt);
            }
        });
        getContentPane().add(Barbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 90, 30));

        JLciudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLciudad.setForeground(new java.awt.Color(255, 255, 255));
        JLciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLciudad.setText("Ciudad:");
        getContentPane().add(JLciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 90, 30));

        JcomboCiudad.setBackground(new java.awt.Color(0, 0, 0));
        JcomboCiudad.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JcomboCiudad.setForeground(new java.awt.Color(255, 255, 255));
        JcomboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "Santo Domingo", "Santiago", "San Cristobal", "San Pedro de Macoris" }));
        JcomboCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JcomboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(JcomboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 270, 50));

        JLexperiencia.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLexperiencia.setForeground(new java.awt.Color(255, 255, 255));
        JLexperiencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLexperiencia.setText("Experiencia:");
        getContentPane().add(JLexperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 130, 30));

        JcomboExperiencia.setBackground(new java.awt.Color(0, 0, 0));
        JcomboExperiencia.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JcomboExperiencia.setForeground(new java.awt.Color(255, 255, 255));
        JcomboExperiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "1 - 6 MESES", "6 - 12 MESES", "1 - 2 AÑOS", "2 - 4 AÑOS", "4 - 8 AÑOS", "8 o MÁS" }));
        JcomboExperiencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(JcomboExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 270, 50));

        JLcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        JLcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcontraseña.setText("Contraseña:");
        getContentPane().add(JLcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, 30));

        JPcontraseña.setBackground(new java.awt.Color(204, 204, 204));
        JPcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JPcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        JPcontraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(JPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 270, 50));

        JPRegistrarse.setBackground(new java.awt.Color(13, 73, 11));
        JPRegistrarse.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        JPRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        JPRegistrarse.setText("Registrarse");
        JPRegistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(JPRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 40));

        JPvolver.setBackground(new java.awt.Color(255, 255, 255));
        JPvolver.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        JPvolver.setForeground(new java.awt.Color(0, 0, 0));
        JPvolver.setText("Volver");
        JPvolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPvolverActionPerformed(evt);
            }
        });
        getContentPane().add(JPvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        JLfondo.setBackground(new java.awt.Color(102, 102, 102));
        JLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        JLfondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        this.dispose();
        new RegistroCliente().setVisible(true);
    }//GEN-LAST:event_ClienteActionPerformed

    private void JTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTemailActionPerformed

    private void BarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarberoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarberoActionPerformed

    private void JTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnombreActionPerformed

    private void JPRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPRegistrarseActionPerformed
       if (!Validaciones.validarNombre(JTnombre)) return;
        if (!Validaciones.validarEmail(JTemail)) return;
        if (!Validaciones.validarCiudad(JcomboCiudad)) return;
        if (!Validaciones.validarTelefono(JFtelefono.getText())) return;
        if (!Validaciones.validarContraseña(JPcontraseña)) return;
        if (!Validaciones.validarTipoUsuario(Cliente.isSelected(), Barbero.isSelected())) return;

        // Datos
        String nombre = JTnombre.getText().trim();
        String email = JTemail.getText().trim();
        String ciudad = (String) JcomboCiudad.getSelectedItem();
        String telefono = JFtelefono.getText().replaceAll("[^0-9]", "");
        String password = new String(JPcontraseña.getPassword());

        // Registrar como peluquero
        boolean exito = RegistroBarbero_Utilidades.registrar(email, password, nombre, telefono, ciudad);
        if (exito) {
             // Limpiar campos
            Validaciones.limpiarCampos(JTnombre, JTemail, JcomboCiudad, JFtelefono, JPcontraseña, Cliente, Barbero);

            this.dispose();
            new MenuBarbero().setVisible(true);
        }
            
    }//GEN-LAST:event_JPRegistrarseActionPerformed

    //Boton de volver, hara que vuelva a IniciarSesion
    private void JPvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPvolverActionPerformed
      this.dispose();
      new IniciarSesion().setVisible(true);
    }//GEN-LAST:event_JPvolverActionPerformed

    private void JcomboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcomboCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroBarbero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroBarbero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroBarbero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroBarbero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroBarbero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Barbero;
    private javax.swing.JRadioButton Cliente;
    private javax.swing.JFormattedTextField JFtelefono;
    private javax.swing.JLabel JLciudad;
    private javax.swing.JLabel JLcontraseña;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLexperiencia;
    private javax.swing.JLabel JLfondo;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtipouser;
    private javax.swing.JLabel JLtitleRegistroBarbe;
    private javax.swing.JButton JPRegistrarse;
    private javax.swing.JPasswordField JPcontraseña;
    private javax.swing.JButton JPvolver;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JComboBox<String> JcomboCiudad;
    private javax.swing.JComboBox<String> JcomboExperiencia;
    private javax.swing.JLabel Nombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
