// thebarbershop.JFrame.RegistroClienteFrame
package thebarbershop.Jframe;

import thebarbershop.utilidades.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jaelj
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public RegistroCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        JPprincipal = new javax.swing.JPanel();
        JLTitleRegistroUser = new javax.swing.JLabel();
        JLnombre = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JLciudad = new javax.swing.JLabel();
        JComboCiudad = new javax.swing.JComboBox<>();
        JLtelefono = new javax.swing.JLabel();
        JFtelefono = new javax.swing.JFormattedTextField();
        JLtipouser = new javax.swing.JLabel();
        Cliente = new javax.swing.JRadioButton();
        Barbero = new javax.swing.JRadioButton();
        JLemail = new javax.swing.JLabel();
        JTemail = new javax.swing.JTextField();
        JBcontraseña = new javax.swing.JLabel();
        JPcontraseña = new javax.swing.JPasswordField();
        JBregistrarse = new javax.swing.JButton();
        JBvolver = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBarberShop - Registro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLTitleRegistroUser.setBackground(new java.awt.Color(255, 255, 255));
        JLTitleRegistroUser.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        JLTitleRegistroUser.setForeground(new java.awt.Color(255, 255, 255));
        JLTitleRegistroUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTitleRegistroUser.setText("Registro de Usuario");
        JPprincipal.add(JLTitleRegistroUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 640, 50));

        JLnombre.setBackground(new java.awt.Color(255, 255, 255));
        JLnombre.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLnombre.setForeground(new java.awt.Color(255, 255, 255));
        JLnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnombre.setText("Nombre:");
        JPprincipal.add(JLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 30));

        JTnombre.setBackground(new java.awt.Color(153, 153, 153));
        JTnombre.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JTnombre.setForeground(new java.awt.Color(0, 0, 0));
        JTnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnombreActionPerformed(evt);
            }
        });
        JPprincipal.add(JTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 270, 50));

        JLciudad.setBackground(new java.awt.Color(255, 255, 255));
        JLciudad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLciudad.setForeground(new java.awt.Color(255, 255, 255));
        JLciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLciudad.setText("Ciudad:");
        JPprincipal.add(JLciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 30));

        JComboCiudad.setBackground(new java.awt.Color(51, 51, 51));
        JComboCiudad.setFont(new java.awt.Font("Copperplate Gothic Light", 2, 14)); // NOI18N
        JComboCiudad.setForeground(new java.awt.Color(255, 255, 255));
        JComboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione....", "Santo Domingo", "Santiago", "San Cristobal", "San Pedro de Macoris" }));
        JComboCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JComboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboCiudadActionPerformed(evt);
            }
        });
        JPprincipal.add(JComboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 270, 50));

        JLtelefono.setBackground(new java.awt.Color(255, 255, 255));
        JLtelefono.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtelefono.setForeground(new java.awt.Color(255, 255, 255));
        JLtelefono.setText("Telefono:");
        JPprincipal.add(JLtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, 30));

        JFtelefono.setBackground(new java.awt.Color(153, 153, 153));
        JFtelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JFtelefono.setForeground(new java.awt.Color(0, 0, 0));
        try {
            JFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFtelefonoActionPerformed(evt);
            }
        });
        JPprincipal.add(JFtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 270, 50));

        JLtipouser.setBackground(new java.awt.Color(255, 255, 255));
        JLtipouser.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLtipouser.setForeground(new java.awt.Color(255, 255, 255));
        JLtipouser.setText("Tipo de usuario:");
        JPprincipal.add(JLtipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, 30));

        buttonGroup1.add(Cliente);
        Cliente.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setSelected(true);
        Cliente.setText("Cliente");
        Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        JPprincipal.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 80, 30));

        buttonGroup1.add(Barbero);
        Barbero.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        Barbero.setForeground(new java.awt.Color(255, 255, 255));
        Barbero.setText("Barbero");
        Barbero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Barbero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Barbero.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Barbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarberoActionPerformed(evt);
            }
        });
        JPprincipal.add(Barbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, 30));

        JLemail.setBackground(new java.awt.Color(255, 255, 255));
        JLemail.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JLemail.setForeground(new java.awt.Color(255, 255, 255));
        JLemail.setText("Email:");
        JPprincipal.add(JLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, 30));

        JTemail.setBackground(new java.awt.Color(153, 153, 153));
        JTemail.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JTemail.setForeground(new java.awt.Color(0, 0, 0));
        JTemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTemailActionPerformed(evt);
            }
        });
        JPprincipal.add(JTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 270, 50));

        JBcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        JBcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        JBcontraseña.setText("Contraseña:");
        JPprincipal.add(JBcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 140, 30));

        JPcontraseña.setBackground(new java.awt.Color(153, 153, 153));
        JPcontraseña.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        JPcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        JPcontraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPprincipal.add(JPcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 270, 50));

        JBregistrarse.setBackground(new java.awt.Color(13, 73, 11));
        JBregistrarse.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBregistrarse.setForeground(new java.awt.Color(255, 255, 255));
        JBregistrarse.setText("Registrarse");
        JBregistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBregistrarseActionPerformed(evt);
            }
        });
        JPprincipal.add(JBregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, 40));

        JBvolver.setBackground(new java.awt.Color(153, 153, 153));
        JBvolver.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        JBvolver.setForeground(new java.awt.Color(51, 51, 51));
        JBvolver.setText("Volver");
        JBvolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBvolver.setPreferredSize(new java.awt.Dimension(79, 25));
        JBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvolverActionPerformed(evt);
            }
        });
        JPprincipal.add(JBvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, -1));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/imagen10(1).jpg"))); // NOI18N
        JPprincipal.add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        getContentPane().add(JPprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnombreActionPerformed

    private void JTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTemailActionPerformed

    private void JComboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboCiudadActionPerformed

    private void JBregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBregistrarseActionPerformed
    // Validaciones
        if (!Validaciones.validarNombre(JTnombre)) return;
        if (!Validaciones.validarEmail(JTemail)) return;
        if (!Validaciones.validarCiudad(JComboCiudad)) return;
        if (!Validaciones.validarTelefono(JFtelefono.getText())) return;
        if (!Validaciones.validarContraseña(JPcontraseña)) return;
        if (!Validaciones.validarTipoUsuario(Cliente.isSelected(), Barbero.isSelected())) return;

        // Datos
        String nombre = JTnombre.getText().trim();
        String email = JTemail.getText().trim();
        String ciudad = (String) JComboCiudad.getSelectedItem();
        String telefono = JFtelefono.getText().replaceAll("[^0-9]", "");
        String password = new String(JPcontraseña.getPassword());

        // Registrar
        boolean exito = RegistroCliente_Utilidades.registrar(email, password, nombre, telefono, ciudad);
        if (exito) {
            // Limpiar campos para nuevo registro 
            Validaciones.limpiarCampos(JTnombre, JTemail, JComboCiudad, JFtelefono, JPcontraseña, Cliente, Barbero);

            this.dispose();
            new MenuCliente().setVisible(true);
        }
    }//GEN-LAST:event_JBregistrarseActionPerformed

    private void JBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvolverActionPerformed
        this.dispose();
        new IniciarSesion().setVisible(true);
    }//GEN-LAST:event_JBvolverActionPerformed

    private void JFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFtelefonoActionPerformed

    private void BarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarberoActionPerformed
        this.dispose();
        new RegistroBarbero().setVisible(true);
    }//GEN-LAST:event_BarberoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Barbero;
    private javax.swing.JRadioButton Cliente;
    private javax.swing.JLabel JBcontraseña;
    private javax.swing.JButton JBregistrarse;
    private javax.swing.JButton JBvolver;
    private javax.swing.JComboBox<String> JComboCiudad;
    private javax.swing.JFormattedTextField JFtelefono;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JLabel JLTitleRegistroUser;
    private javax.swing.JLabel JLciudad;
    private javax.swing.JLabel JLemail;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtipouser;
    private javax.swing.JPasswordField JPcontraseña;
    private javax.swing.JPanel JPprincipal;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTnombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
